### ISSUE TITLE
Plugin breaks sourcemaps on Google Chrome

### ISSUE THREAD

**Issue by sprguillen** [sheerun/targets-webpack-plugin#3]
As stated in the README: This plugin runs babel and rollup only once per asset, at the end of the compilation process.

Works like a charm as it runs my VueJS app on IE but the problem is that it breaks sourcemaps on Chrome: here's a more elaborate article on [stackoverflow](https://stackoverflow.com/questions/53266599/vuejs-application-doesnt-load-on-internet-explorer?noredirect=1#comment93417421_53266599).

Maybe you can address this if you have plans to update the module. Thanks!

**Comment by sheerun** [comment]
Maybe you want to prepare and test the fix? I forked from other project where PR fixing this is available: https://github.com/simlrh/babel-webpack-plugin/pull/2/files

**Comment by sprguillen** [comment]
You mean I'll use babel-webpack-plugin in-conjunction with targets-webpack-plugin?

**Comment by sheerun** [comment]
I mean to submit PR to this repository fixing this issue. You can find fix for repository I forked from in the link I've sent before

**Comment by sheerun** [comment]
The issue is not with PR but with testing if it really works and that could be your part

**Comment by sprguillen** [comment]
Hey, I forked the project and revised the project not only with the link above but also added the lines where  sourceMaps are referenced, it didn't work either.. You might want to see my revision?

**Comment by sprguillen** [comment]
I made some revisions to no avail. The PR isn't as simple as we thought it might because it requires us to use `SourceMapSource `instead of `OriginalSource `which need us to have an `inputSourceMap `defined. Adding the line where `asset.sourceAndMap` will be defined would lead to a **Javascript heap out of memory** error. I don't know if I'm doing it right since I did not author this module..

**Comment by sprguillen** [comment]
Reference to the changes I've applied are on this [link](https://github.com/simlrh/babel-webpack-plugin/blob/01a566040076d709d883302c49de9c93800c4fb3/index.js).

**Comment by sheerun** [comment]
@sprguillen I've published 2.0.0-alpha.0 which should have sourcemaps support. Do you want to test it?

**Comment by sprguillen** [comment]
Great! Thanks, I'll gladly test it for you.

**Comment by sprguillen** [comment]
I keep getting `Cannot find module 'webpack-sources'` error and running `yarn add webpack-sources` doesn't help either..

**Comment by sprguillen** [comment]
![2018-11-15_1314](https://user-images.githubusercontent.com/1183103/48531770-8f539680-e8d8-11e8-944b-9bca2ea8c2c4.png)

I got this error, it's quite similar after I tried to applied the fix you mentioned..

**Comment by sheerun** [comment]
Strange, webpack-source is in package.json so it should be installed. Maybe
try to reinstall everything.

I've just published 2.0.0-alpha.1 maybe it's better. If not maybe you could
experiment in code I've pushed to master and send fixing PR?

**Comment by sprguillen** [comment]
Sorry my fault on webpack-source. I wasnt using 2.0 alpha but the Javascript heap out of memory is now happening on 2.0.0 alpha...

**Comment by sheerun** [comment]
Did you try 2.0.0-alpha.1  ?

**Comment by sprguillen** [comment]
Yes, that's the one causing the error..

**Comment by sheerun** [comment]
I think it's simply because sourcemaps are generated and you don't have enough memory. You can pass { sourceMaps: false } to disable generating sourcemaps but in general you should disable it for development

**Comment by sheerun** [comment]
Does it fail on CI as well?

**Comment by sprguillen** [comment]
I haven't tried on CI. We actually need it more on deployment rather than in production. :) I think bundling for legacy browsers + sourcemaps overloads NodeJS.

**Comment by sprguillen** [comment]
I haven't tried on CI. We actually need sourcemaps more on development rather than in production. :) I think bundling for legacy browsers + sourcemaps overloads NodeJS.

**Comment by sheerun** [comment]
FYI it works for me on my CI, and on my OSX but I have 16GB ram

**Comment by sprguillen** [comment]
What's your current setup? I'm currently using Windows, Node 10.9.0..

I actually have 16gb ram as well.. CI means continuous integration right? I'm currently not using any CI tools. Just `yarn` or `npm`.

**Comment by sheerun** [comment]
Yes it means something like travis that deploys the service

**Comment by sprguillen** [comment]
I think it does make the difference, I don't use any CI tool and maybe that's why I have those heap issues. This plugin when sourceMap enabled may only be compatible with having been deployed by Travis.. Have you tried it without using Travis? Just running the node server using `yarn` or `npm`? Does it work?

**Comment by sheerun** [comment]
As I said it works both on my CI (I'm using server on scaleway), and on my
OSX machine.

**Comment by sprguillen** [comment]
We made some changes on the webpack configuration and tested on 2.0.0-alpha.1, it successfully worked! Good job! Closing this issue now..

**Comment by sheerun** [comment]
Glad to hear :) Mind to tell what changes?

**Comment by sprguillen** [comment]
We used the webpack-bundle-analyzer and restructured how plugins are being loaded by webpack, that may have reduced the amount of memory webpack is consuming when compiling code.
